created workflows, additional file mods
plus3it/terraform-aws-tardigrade-config-rules pull request #176
Opened 2023-02-07 15:55 UTC by dalerichardson

2023-02-07 17:35 UTC, lorengordon requested changes

2023-02-07 17:51 UTC, dalerichardson commented on .github/workflows/release.yml
> +      release-token: ${{ secrets.GH_RELEASES_TOKEN }}
When I pushed it to my fork, the mockstacktest failed. See - https://github.com/plus3it/terraform-aws-tardigrade-config-rules/actions/runs/4115735014/jobs/7104850693

2023-02-07 17:52 UTC, dalerichardson commented on .github/workflows/release.yml
> +      release-token: ${{ secrets.GH_RELEASES_TOKEN }}
Then I added the disable mockstack test logic

2023-02-07 18:07 UTC, lorengordon commented on .github/workflows/release.yml
> +      release-token: ${{ secrets.GH_RELEASES_TOKEN }}
Yeah, that's a weird error though, just saying it cannot connect. Might have been a race condition. It is working now, so we can remove it and make that a required workflow.

2023-02-07 18:13 UTC, dalerichardson commented on .github/workflows/release.yml
> +      release-token: ${{ secrets.GH_RELEASES_TOKEN }}
Sounds good. Will remove disable logic.

2023-02-08 14:37 UTC, dalerichardson commented on .github/workflows/lint.yml
> +    uses: plus3it/actions-workflows/.github/workflows/lint.yml@41056300ba78d8be98b45f057aea246f8c4f30cf
Can you clarify? You are referring to the @sha value we set here?

2023-02-08 15:12 UTC, lorengordon commented on .github/workflows/lint.yml
> +    uses: plus3it/actions-workflows/.github/workflows/lint.yml@41056300ba78d8be98b45f057aea246f8c4f30cf
Yes, the sha value. The current value is for v1.0.0 of the actions-workflows project. We released v1.0.1 on Monday. So these values need to be updated to the sha for v1.0.1.

2023-02-08 15:31 UTC, dalerichardson commented on .github/workflows/lint.yml
> +    uses: plus3it/actions-workflows/.github/workflows/lint.yml@41056300ba78d8be98b45f057aea246f8c4f30cf
Got it, thanks

2023-02-08 16:05 UTC, lorengordon approved these changes
Looks good!

2023-02-08 16:10 UTC, merged